#!/bin/bash

# wallpaper
swww-daemon &
swww img ~/.config/hypr/wallpaper.png &

# waybar
waybar &

# notifications
swaync &

# osd
swayosd-server &

# plugins
hyprpm reload -n &

# terminal images
ueverzug layer &

# splash
~/.config/hypr/splashswitch.sh &

# dock
nwg-dock-hyprland -mb 10 -c wofi -ico ~/.config/nwg-dock-hyprland/arch.png
