#!/bin/bash

# wallpaper
swww-daemon &

# bar
waybar &

# winswitch
hyprswitch init

# plugins
hyprpm reload -n &

# terminal images
ueverzug layer &

# splash
~/.config/hypr/splashswitch.sh &

# idle
hypridle &

# dropdown term
pypr &

# notifications
swaync &

# osd
swayosd-server &
