#!/bin/bash

# wallpaper
swww-daemon &
swww img ~/.config/hypr/wallpaper.png &

# ags
ags &

# osd
swayosd-server &

# plugins
hyprpm reload -n &

# terminal images
ueverzug layer &

# splash
~/.config/hypr/splashswitch.sh &

